class_name LevelData
extends RefCounted

# ---------------------------------------------------------------------------
# TILE GRID
#   TILE            one grid square, 54x54
#   a shelf row     3 tiles tall (SHELF_SPACING = 162 = 3 * TILE)
#   "col"           horizontal tile index, 0 = leftmost
#   "shelf"         0 = standing on the aisle floor, counting upwards
# ---------------------------------------------------------------------------

const TILE          := 54.0    # 3x the 18px Kenney tiles, so pixels stay square
const SHELF_SPACING := 162.0   # 3 tiles
const BOARD_HEIGHT  := 16.0
const FLOOR_Y       := 600.0
const DEFAULT_COLS  := 34

# ---------------------------------------------------------------------------
# SPRITE SHEETS
# Drop the PNGs into res://sprites/ using exactly these filenames. Anything
# without a sheet falls back to procedural shapes, so the game runs with no art.
# ---------------------------------------------------------------------------

static func sheets() -> Dictionary:
	return {
		"industrial.png": {"tile_w": 18, "tile_h": 18, "margin": 0, "spacing": 0, "cols": 16},
		"grocery.png": {"tile_w": 96, "tile_h": 96, "margin": 0, "spacing": 0, "cols": 7},
	}


# ---------------------------------------------------------------------------
# LEVELS
#
# cols / shelves  aisle size in tiles
# order           "fixed" | "shuffle" | "any"
# randomise       true = item positions are scattered fresh every run
# pick            if > 0, the list is N items drawn at random from the shelves
#
# hazards         "type" drives BEHAVIOUR, not just looks:
#                   peel    1.0s stun, you skid with no controls
#                   spill   slowdown, still steerable
#                   ice     3.0s slip - faster but barely steerable
#                   soap    1.8s trapped in a bubble, pinned
#                   crate / trolley / pallet   generic solid, slowdown
#
# doors           frosted freezer panes drawn OVER the aisle, visual only
# gaps            individual missing board tiles; adjacent ones merge
# ---------------------------------------------------------------------------

static func levels() -> Array:
	return [
		{
			"name": "1 - Produce Pursuit",
			"cols": 34,
			"shelves": 4,
			"order": "shuffle",
			"randomise": true,
			"items": [
				{"id": "apples", "label": "Apples", "coins": 1, "type": "apple", "shelf": 1, "col": 15,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.APPLE_RED},
				{"id": "strawberries", "label": "Strawberries", "coins": 1, "type": "strawberry", "shelf": 0, "col": 6,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.STRAWBERRY},
				{"id": "carrots", "label": "Carrots", "coins": 2, "type": "carrot", "shelf": 2, "col": 9,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.CARROT},
				{"id": "broccoli", "label": "Broccoli", "coins": 2, "type": "broccoli", "shelf": 1, "col": 26,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.BROCCOLI},
				{"id": "tomatoes", "label": "Tomatoes", "coins": 3, "type": "tomato", "shelf": 3, "col": 19,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.TOMATO},
				{"id": "cabbage", "label": "Cabbage", "coins": 1, "type": "cabbage", "shelf": 0, "col": 28,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.CABBAGE},
				{"id": "oranges", "label": "Oranges", "coins": 3, "type": "orange", "shelf": 2, "col": 30,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.ORANGE},
				{"id": "grapes", "label": "Grapes", "coins": 4, "type": "grapes", "shelf": 3, "col": 31,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.GRAPES},
			],
			# A mix of "peel" (flat sprite, low box, stun) and "crate" (square
			# sprite, square box, slowdown) so twelve hazards don't read as the
			# same banana repeated twelve times, and no icon gets squashed into
			# a hitbox shaped wrong for it - see GroceryTheme's hazard comments.
			"hazards": [
				{"type": "peel", "shelf": 0, "col": 7, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.PEEL_ANGRY},
				{"type": "crate", "shelf": 0, "col": 12, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.APPLE_ANGRY},
				{"type": "crate", "shelf": 0, "col": 31, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.PEAR_ANGRY},
				{"type": "crate", "shelf": 1, "col": 8, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.BROCCOLI_ANGRY},
				{"type": "crate", "shelf": 1, "col": 18, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.CARROT_ANGRY},
				{"type": "crate", "shelf": 1, "col": 23, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.CABBAGE_ANGRY},
				{"type": "crate", "shelf": 2, "col": 11, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.CORN_ANGRY},
				{"type": "peel", "shelf": 2, "col": 19, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.TOMATO_ANGRY},
				{"type": "crate", "shelf": 2, "col": 31, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.ORANGE_ANGRY},
				{"type": "crate", "shelf": 3, "col": 17, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.STRAWBERRY_ANGRY},
				{"type": "peel", "shelf": 3, "col": 24, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.PEEL_ANGRY},
				{"type": "crate", "shelf": 3, "col": 29, "sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.APPLE_ANGRY},
			],
			"powerups": [
				{"id": "pu1", "kind": "boost", "label": "Golden Apple", "shelf": 2, "col": 4,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.APPLE_GOLDEN},
				{"id": "pu2", "kind": "clean", "label": "Fresh Wash", "shelf": 1, "col": 2,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.PEAR_FROZEN},
				{"id": "pu3", "kind": "coins", "label": "Crown Broccoli", "shelf": 3, "col": 4,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.BROCCOLI_KING},
				{"id": "pu4", "kind": "coins", "label": "Baked Beans", "shelf": 0, "col": 20,
					"sheet": GroceryTheme.SHEET, "sprite": GroceryTheme.BEANS_CAN},
			],
			"gaps": [
				{"shelf": 2, "col": 19},
				{"shelf": 2, "col": 20},
				{"shelf": 3, "col": 25},
				{"shelf": 3, "col": 26},
			],
			"list": ["strawberries", "apples", "carrots", "broccoli", "tomatoes", "cabbage"],
		},
		{
			"name": "2 - Snack Attack",
			"cols": 38,
			"shelves": 5,
			"order": "shuffle",
			"randomise": true,
			"items": [
				{"id": "chocbar", "label": "Choc Bar", "coins": 1, "type": "chocolate", "shelf": 0, "col": 7},
				{"id": "gummies", "label": "Gummy Bears", "coins": 2, "type": "gummy", "shelf": 1, "col": 18},
				{"id": "truffles", "label": "Truffles", "coins": 3, "type": "chocolate", "shelf": 2, "col": 12},
				{"id": "lollipop", "label": "Lollipop", "coins": 2, "type": "lollipop", "shelf": 3, "col": 24},
				{"id": "jellybeans", "label": "Jelly Beans", "coins": 3, "type": "candy", "shelf": 1, "col": 31},
				{"id": "marshmallows", "label": "Marshmallows", "coins": 2, "type": "marshmallow", "shelf": 4, "col": 16},
				{"id": "toffees", "label": "Toffees", "coins": 4, "type": "candy", "shelf": 4, "col": 33},
				{"id": "mints", "label": "Mints", "coins": 1, "type": "candy", "shelf": 0, "col": 29},
			],
			"hazards": [
				{"type": "spill", "shelf": 0, "col": 19},
				{"type": "spill", "shelf": 0, "col": 22},
				{"type": "spill", "shelf": 0, "col": 25},
				{"type": "spill", "shelf": 1, "col": 10},
				{"type": "spill", "shelf": 1, "col": 13},
				{"type": "spill", "shelf": 1, "col": 34},
				{"type": "spill", "shelf": 2, "col": 10},
				{"type": "spill", "shelf": 2, "col": 14},
				{"type": "spill", "shelf": 2, "col": 21},
				{"type": "spill", "shelf": 3, "col": 10},
				{"type": "spill", "shelf": 3, "col": 19},
				{"type": "spill", "shelf": 3, "col": 26},
				{"type": "spill", "shelf": 4, "col": 7},
				{"type": "spill", "shelf": 4, "col": 13},
				{"type": "spill", "shelf": 4, "col": 22},
			],
			"powerups": [
				{"id": "pu2", "kind": "clean", "label": "Mop", "shelf": 1, "col": 5},
				{"id": "pu3", "kind": "boost", "label": "Energy Drink", "shelf": 3, "col": 35},
			],
			"gaps": [
				{"shelf": 1, "col": 22},
				{"shelf": 1, "col": 23},
				{"shelf": 2, "col": 29},
				{"shelf": 2, "col": 30},
				{"shelf": 3, "col": 11},
				{"shelf": 3, "col": 12},
				{"shelf": 4, "col": 25},
				{"shelf": 4, "col": 26},
			],
			"list": ["chocbar", "gummies", "truffles", "lollipop", "jellybeans", "marshmallows"],
		},
		{
			"name": "3 - Frozen Frenzy",
			"cols": 42,
			"shelves": 6,
			"order": "shuffle",
			"randomise": true,
			"items": [
				{"id": "chicken", "label": "Chicken", "coins": 2, "type": "poultry", "shelf": 0, "col": 8},
				{"id": "turkey", "label": "Turkey Crown", "coins": 3, "type": "poultry", "shelf": 1, "col": 21},
				{"id": "vanillatub", "label": "Vanilla Tub", "coins": 2, "type": "icecream", "shelf": 2, "col": 13},
				{"id": "chocice", "label": "Choc Ice", "coins": 3, "type": "icecream", "shelf": 3, "col": 27},
				{"id": "icepop", "label": "Ice Pops", "coins": 1, "type": "icepop", "shelf": 1, "col": 33},
				{"id": "sorbet", "label": "Sorbet", "coins": 4, "type": "icecream", "shelf": 4, "col": 18},
				{"id": "nuggets", "label": "Nuggets", "coins": 2, "type": "poultry", "shelf": 4, "col": 36},
				{"id": "gateau", "label": "Ice Gateau", "coins": 5, "type": "icecream", "shelf": 5, "col": 30},
			],
			"hazards": [
				{"type": "ice", "shelf": 0, "col": 20},
				{"type": "ice", "shelf": 0, "col": 29},
				{"type": "ice", "shelf": 0, "col": 37},
				{"type": "ice", "shelf": 1, "col": 7},
				{"type": "ice", "shelf": 1, "col": 31},
				{"type": "ice", "shelf": 1, "col": 35},
				{"type": "ice", "shelf": 2, "col": 10},
				{"type": "ice", "shelf": 2, "col": 27},
				{"type": "ice", "shelf": 2, "col": 36},
				{"type": "ice", "shelf": 3, "col": 11},
				{"type": "ice", "shelf": 3, "col": 34},
				{"type": "ice", "shelf": 3, "col": 38},
				{"type": "ice", "shelf": 4, "col": 24},
				{"type": "ice", "shelf": 4, "col": 27},
				{"type": "ice", "shelf": 4, "col": 38},
				{"type": "ice", "shelf": 5, "col": 8},
				{"type": "ice", "shelf": 5, "col": 20},
				{"type": "ice", "shelf": 5, "col": 26},
			],
			"powerups": [
				{"id": "pu4", "kind": "clean", "label": "Grit Salt", "shelf": 2, "col": 4},
				{"id": "pu5", "kind": "coins", "label": "Clubcard", "shelf": 5, "col": 8},
			],
			"doors": [
				{"shelf": 2, "col": 10},
				{"shelf": 2, "col": 11},
				{"shelf": 2, "col": 12},
				{"shelf": 2, "col": 13},
				{"shelf": 2, "col": 14},
				{"shelf": 2, "col": 15},
				{"shelf": 2, "col": 16},
				{"shelf": 2, "col": 17},
				{"shelf": 3, "col": 24},
				{"shelf": 3, "col": 25},
				{"shelf": 3, "col": 26},
				{"shelf": 3, "col": 27},
				{"shelf": 3, "col": 28},
				{"shelf": 3, "col": 29},
				{"shelf": 3, "col": 30},
				{"shelf": 3, "col": 31},
				{"shelf": 4, "col": 14},
				{"shelf": 4, "col": 15},
				{"shelf": 4, "col": 16},
				{"shelf": 4, "col": 17},
				{"shelf": 4, "col": 18},
				{"shelf": 4, "col": 19},
				{"shelf": 4, "col": 20},
				{"shelf": 4, "col": 21},
				{"shelf": 5, "col": 27},
				{"shelf": 5, "col": 28},
				{"shelf": 5, "col": 29},
				{"shelf": 5, "col": 30},
				{"shelf": 5, "col": 31},
				{"shelf": 5, "col": 32},
				{"shelf": 5, "col": 33},
				{"shelf": 5, "col": 34},
				{"shelf": 1, "col": 30},
				{"shelf": 1, "col": 31},
				{"shelf": 1, "col": 32},
				{"shelf": 1, "col": 33},
				{"shelf": 1, "col": 34},
				{"shelf": 1, "col": 35},
				{"shelf": 1, "col": 36},
			],
			"gaps": [
				{"shelf": 1, "col": 27},
				{"shelf": 1, "col": 28},
				{"shelf": 2, "col": 15},
				{"shelf": 2, "col": 16},
				{"shelf": 3, "col": 33},
				{"shelf": 3, "col": 34},
				{"shelf": 4, "col": 10},
				{"shelf": 4, "col": 11},
				{"shelf": 5, "col": 22},
				{"shelf": 5, "col": 23},
			],
			"list": ["chicken", "turkey", "vanillatub", "chocice", "icepop", "sorbet"],
		},
		{
			"name": "4 - Health & Beauty",
			"cols": 38,
			"shelves": 5,
			"order": "shuffle",
			"randomise": true,
			"items": [
				{"id": "hairbrush", "label": "Hairbrush", "coins": 1, "type": "hairbrush", "shelf": 0, "col": 6},
				{"id": "comb", "label": "Comb", "coins": 1, "type": "comb", "shelf": 1, "col": 17},
				{"id": "lipstick", "label": "Lipstick", "coins": 3, "type": "lipstick", "shelf": 2, "col": 11},
				{"id": "mascara", "label": "Mascara", "coins": 3, "type": "mascara", "shelf": 3, "col": 25},
				{"id": "foundation", "label": "Foundation", "coins": 4, "type": "foundation", "shelf": 2, "col": 32},
				{"id": "nailpolish", "label": "Nail Polish", "coins": 2, "type": "nailpolish", "shelf": 4, "col": 20},
				{"id": "blusher", "label": "Blusher", "coins": 3, "type": "blusher", "shelf": 4, "col": 34},
				{"id": "shampoo", "label": "Shampoo", "coins": 1, "type": "shampoo", "shelf": 0, "col": 30},
			],
			"hazards": [
				{"type": "soap", "shelf": 0, "col": 9},
				{"type": "soap", "shelf": 0, "col": 19},
				{"type": "soap", "shelf": 0, "col": 29},
				{"type": "soap", "shelf": 1, "col": 22},
				{"type": "soap", "shelf": 1, "col": 25},
				{"type": "soap", "shelf": 1, "col": 28},
				{"type": "soap", "shelf": 2, "col": 12},
				{"type": "soap", "shelf": 2, "col": 26},
				{"type": "soap", "shelf": 2, "col": 30},
				{"type": "soap", "shelf": 3, "col": 12},
				{"type": "soap", "shelf": 3, "col": 32},
				{"type": "soap", "shelf": 3, "col": 35},
				{"type": "soap", "shelf": 4, "col": 7},
				{"type": "soap", "shelf": 4, "col": 16},
				{"type": "soap", "shelf": 4, "col": 26},
			],
			"powerups": [
				{"id": "pu6", "kind": "boost", "label": "Energy Drink", "shelf": 1, "col": 4},
				{"id": "pu7", "kind": "coins", "label": "Clubcard", "shelf": 4, "col": 6},
			],
			"gaps": [
				{"shelf": 1, "col": 13},
				{"shelf": 1, "col": 14},
				{"shelf": 2, "col": 26},
				{"shelf": 2, "col": 27},
				{"shelf": 3, "col": 18},
				{"shelf": 3, "col": 19},
				{"shelf": 4, "col": 29},
				{"shelf": 4, "col": 30},
			],
			"list": ["hairbrush", "comb", "lipstick", "mascara", "foundation", "nailpolish"],
		},
		{
			"name": "5 - All-Store Pick",
			"cols": 161,
			"shelves": 6,
			"order": "shuffle",
			"randomise": true,
			"pick": 10,
			"sections": [
				{"col": 0, "name": "Produce"},
				{"col": 37, "name": "Snacks"},
				{"col": 78, "name": "Frozen"},
				{"col": 123, "name": "Health & Beauty"},
			],
			"items": [
				{"id": "banana", "label": "Bananas", "coins": 1, "type": "banana", "shelf": 0, "col": 6},
				{"id": "apples", "label": "Apples", "coins": 1, "type": "apple", "shelf": 1, "col": 15},
				{"id": "carrots", "label": "Carrots", "coins": 2, "type": "carrot", "shelf": 2, "col": 9},
				{"id": "broccoli", "label": "Broccoli", "coins": 2, "type": "broccoli", "shelf": 1, "col": 26},
				{"id": "tomatoes", "label": "Tomatoes", "coins": 3, "type": "tomato", "shelf": 3, "col": 19},
				{"id": "potatoes", "label": "Potatoes", "coins": 1, "type": "potato", "shelf": 0, "col": 28},
				{"id": "lemons", "label": "Lemons", "coins": 3, "type": "lemon", "shelf": 2, "col": 30},
				{"id": "grapes", "label": "Grapes", "coins": 4, "type": "grapes", "shelf": 3, "col": 31},
				{"id": "chocbar", "label": "Choc Bar", "coins": 1, "type": "chocolate", "shelf": 0, "col": 44},
				{"id": "gummies", "label": "Gummy Bears", "coins": 2, "type": "gummy", "shelf": 1, "col": 55},
				{"id": "truffles", "label": "Truffles", "coins": 3, "type": "chocolate", "shelf": 2, "col": 49},
				{"id": "lollipop", "label": "Lollipop", "coins": 2, "type": "lollipop", "shelf": 3, "col": 61},
				{"id": "jellybeans", "label": "Jelly Beans", "coins": 3, "type": "candy", "shelf": 1, "col": 68},
				{"id": "marshmallows", "label": "Marshmallows", "coins": 2, "type": "marshmallow", "shelf": 4, "col": 53},
				{"id": "toffees", "label": "Toffees", "coins": 4, "type": "candy", "shelf": 4, "col": 70},
				{"id": "mints", "label": "Mints", "coins": 1, "type": "candy", "shelf": 0, "col": 66},
				{"id": "chicken", "label": "Chicken", "coins": 2, "type": "poultry", "shelf": 0, "col": 86},
				{"id": "turkey", "label": "Turkey Crown", "coins": 3, "type": "poultry", "shelf": 1, "col": 99},
				{"id": "vanillatub", "label": "Vanilla Tub", "coins": 2, "type": "icecream", "shelf": 2, "col": 91},
				{"id": "chocice", "label": "Choc Ice", "coins": 3, "type": "icecream", "shelf": 3, "col": 105},
				{"id": "icepop", "label": "Ice Pops", "coins": 1, "type": "icepop", "shelf": 1, "col": 111},
				{"id": "sorbet", "label": "Sorbet", "coins": 4, "type": "icecream", "shelf": 4, "col": 96},
				{"id": "nuggets", "label": "Nuggets", "coins": 2, "type": "poultry", "shelf": 4, "col": 114},
				{"id": "gateau", "label": "Ice Gateau", "coins": 5, "type": "icecream", "shelf": 5, "col": 108},
				{"id": "hairbrush", "label": "Hairbrush", "coins": 1, "type": "hairbrush", "shelf": 0, "col": 129},
				{"id": "comb", "label": "Comb", "coins": 1, "type": "comb", "shelf": 1, "col": 140},
				{"id": "lipstick", "label": "Lipstick", "coins": 3, "type": "lipstick", "shelf": 2, "col": 134},
				{"id": "mascara", "label": "Mascara", "coins": 3, "type": "mascara", "shelf": 3, "col": 148},
				{"id": "foundation", "label": "Foundation", "coins": 4, "type": "foundation", "shelf": 2, "col": 155},
				{"id": "nailpolish", "label": "Nail Polish", "coins": 2, "type": "nailpolish", "shelf": 4, "col": 143},
				{"id": "blusher", "label": "Blusher", "coins": 3, "type": "blusher", "shelf": 4, "col": 157},
				{"id": "shampoo", "label": "Shampoo", "coins": 1, "type": "shampoo", "shelf": 0, "col": 153},
			],
			"hazards": [
				{"type": "peel", "shelf": 0, "col": 7},
				{"type": "peel", "shelf": 0, "col": 12},
				{"type": "peel", "shelf": 0, "col": 31},
				{"type": "peel", "shelf": 1, "col": 8},
				{"type": "peel", "shelf": 1, "col": 18},
				{"type": "peel", "shelf": 1, "col": 23},
				{"type": "peel", "shelf": 2, "col": 11},
				{"type": "peel", "shelf": 2, "col": 19},
				{"type": "peel", "shelf": 2, "col": 31},
				{"type": "peel", "shelf": 3, "col": 17},
				{"type": "peel", "shelf": 3, "col": 24},
				{"type": "peel", "shelf": 3, "col": 29},
				{"type": "spill", "shelf": 0, "col": 56},
				{"type": "spill", "shelf": 0, "col": 59},
				{"type": "spill", "shelf": 0, "col": 62},
				{"type": "spill", "shelf": 1, "col": 47},
				{"type": "spill", "shelf": 1, "col": 50},
				{"type": "spill", "shelf": 1, "col": 71},
				{"type": "spill", "shelf": 2, "col": 47},
				{"type": "spill", "shelf": 2, "col": 51},
				{"type": "spill", "shelf": 2, "col": 58},
				{"type": "spill", "shelf": 3, "col": 47},
				{"type": "spill", "shelf": 3, "col": 56},
				{"type": "spill", "shelf": 3, "col": 63},
				{"type": "spill", "shelf": 4, "col": 44},
				{"type": "spill", "shelf": 4, "col": 50},
				{"type": "spill", "shelf": 4, "col": 59},
				{"type": "ice", "shelf": 0, "col": 98},
				{"type": "ice", "shelf": 0, "col": 107},
				{"type": "ice", "shelf": 0, "col": 115},
				{"type": "ice", "shelf": 1, "col": 85},
				{"type": "ice", "shelf": 1, "col": 109},
				{"type": "ice", "shelf": 1, "col": 113},
				{"type": "ice", "shelf": 2, "col": 88},
				{"type": "ice", "shelf": 2, "col": 105},
				{"type": "ice", "shelf": 2, "col": 114},
				{"type": "ice", "shelf": 3, "col": 89},
				{"type": "ice", "shelf": 3, "col": 112},
				{"type": "ice", "shelf": 3, "col": 116},
				{"type": "ice", "shelf": 4, "col": 102},
				{"type": "ice", "shelf": 4, "col": 105},
				{"type": "ice", "shelf": 4, "col": 116},
				{"type": "ice", "shelf": 5, "col": 86},
				{"type": "ice", "shelf": 5, "col": 98},
				{"type": "ice", "shelf": 5, "col": 104},
				{"type": "soap", "shelf": 0, "col": 132},
				{"type": "soap", "shelf": 0, "col": 142},
				{"type": "soap", "shelf": 0, "col": 152},
				{"type": "soap", "shelf": 1, "col": 145},
				{"type": "soap", "shelf": 1, "col": 148},
				{"type": "soap", "shelf": 1, "col": 151},
				{"type": "soap", "shelf": 2, "col": 135},
				{"type": "soap", "shelf": 2, "col": 149},
				{"type": "soap", "shelf": 2, "col": 153},
				{"type": "soap", "shelf": 3, "col": 135},
				{"type": "soap", "shelf": 3, "col": 155},
				{"type": "soap", "shelf": 3, "col": 158},
				{"type": "soap", "shelf": 4, "col": 130},
				{"type": "soap", "shelf": 4, "col": 139},
				{"type": "soap", "shelf": 4, "col": 149},
			],
			"powerups": [
				{"id": "p5a", "kind": "boost", "label": "Energy Drink", "shelf": 0, "col": 3},
				{"id": "p5b", "kind": "clean", "label": "Mop", "shelf": 1, "col": 42},
				{"id": "p5c", "kind": "clean", "label": "Grit Salt", "shelf": 2, "col": 86},
				{"id": "p5d", "kind": "coins", "label": "Clubcard", "shelf": 3, "col": 152},
				{"id": "p5e", "kind": "boost", "label": "Energy Drink", "shelf": 4, "col": 131},
			],
			"doors": [
				{"shelf": 2, "col": 88},
				{"shelf": 2, "col": 89},
				{"shelf": 2, "col": 90},
				{"shelf": 2, "col": 91},
				{"shelf": 2, "col": 92},
				{"shelf": 2, "col": 93},
				{"shelf": 2, "col": 94},
				{"shelf": 2, "col": 95},
				{"shelf": 3, "col": 102},
				{"shelf": 3, "col": 103},
				{"shelf": 3, "col": 104},
				{"shelf": 3, "col": 105},
				{"shelf": 3, "col": 106},
				{"shelf": 3, "col": 107},
				{"shelf": 3, "col": 108},
				{"shelf": 3, "col": 109},
				{"shelf": 4, "col": 92},
				{"shelf": 4, "col": 93},
				{"shelf": 4, "col": 94},
				{"shelf": 4, "col": 95},
				{"shelf": 4, "col": 96},
				{"shelf": 4, "col": 97},
				{"shelf": 4, "col": 98},
				{"shelf": 4, "col": 99},
				{"shelf": 5, "col": 105},
				{"shelf": 5, "col": 106},
				{"shelf": 5, "col": 107},
				{"shelf": 5, "col": 108},
				{"shelf": 5, "col": 109},
				{"shelf": 5, "col": 110},
				{"shelf": 5, "col": 111},
				{"shelf": 5, "col": 112},
			],
			"gaps": [
				{"shelf": 1, "col": 34},
				{"shelf": 1, "col": 35},
				{"shelf": 1, "col": 36},
				{"shelf": 1, "col": 59},
				{"shelf": 1, "col": 60},
				{"shelf": 1, "col": 75},
				{"shelf": 1, "col": 76},
				{"shelf": 1, "col": 77},
				{"shelf": 1, "col": 105},
				{"shelf": 1, "col": 106},
				{"shelf": 1, "col": 120},
				{"shelf": 1, "col": 121},
				{"shelf": 1, "col": 122},
				{"shelf": 1, "col": 136},
				{"shelf": 1, "col": 137},
				{"shelf": 2, "col": 19},
				{"shelf": 2, "col": 20},
				{"shelf": 2, "col": 34},
				{"shelf": 2, "col": 35},
				{"shelf": 2, "col": 36},
				{"shelf": 2, "col": 66},
				{"shelf": 2, "col": 67},
				{"shelf": 2, "col": 75},
				{"shelf": 2, "col": 76},
				{"shelf": 2, "col": 77},
				{"shelf": 2, "col": 93},
				{"shelf": 2, "col": 94},
				{"shelf": 2, "col": 120},
				{"shelf": 2, "col": 121},
				{"shelf": 2, "col": 122},
				{"shelf": 2, "col": 149},
				{"shelf": 2, "col": 150},
				{"shelf": 3, "col": 25},
				{"shelf": 3, "col": 26},
				{"shelf": 3, "col": 34},
				{"shelf": 3, "col": 35},
				{"shelf": 3, "col": 36},
				{"shelf": 3, "col": 48},
				{"shelf": 3, "col": 49},
				{"shelf": 3, "col": 75},
				{"shelf": 3, "col": 76},
				{"shelf": 3, "col": 77},
				{"shelf": 3, "col": 111},
				{"shelf": 3, "col": 112},
				{"shelf": 3, "col": 120},
				{"shelf": 3, "col": 121},
				{"shelf": 3, "col": 122},
				{"shelf": 3, "col": 141},
				{"shelf": 3, "col": 142},
				{"shelf": 4, "col": 34},
				{"shelf": 4, "col": 35},
				{"shelf": 4, "col": 36},
				{"shelf": 4, "col": 62},
				{"shelf": 4, "col": 63},
				{"shelf": 4, "col": 75},
				{"shelf": 4, "col": 76},
				{"shelf": 4, "col": 77},
				{"shelf": 4, "col": 88},
				{"shelf": 4, "col": 89},
				{"shelf": 4, "col": 120},
				{"shelf": 4, "col": 121},
				{"shelf": 4, "col": 122},
				{"shelf": 4, "col": 152},
				{"shelf": 4, "col": 153},
				{"shelf": 5, "col": 34},
				{"shelf": 5, "col": 35},
				{"shelf": 5, "col": 36},
				{"shelf": 5, "col": 75},
				{"shelf": 5, "col": 76},
				{"shelf": 5, "col": 77},
				{"shelf": 5, "col": 100},
				{"shelf": 5, "col": 101},
				{"shelf": 5, "col": 120},
				{"shelf": 5, "col": 121},
				{"shelf": 5, "col": 122},
			],
			"list": [],
		},
	]
